
resilience4j:
    circuitbreaker:
        configs:
            default:
                slidingWindowSize: 6
                failureRateThreshold: 50
                waitDurationInOpenState: 20s
                permittedNumberOfCallsInHalfOpenState: 4
                slow-call-duration-threshold: 3s
                slow-call-rate-threshold: 50
        instances:
            products:
                baseConfig: default
    timelimiter:
        configs:
            default:
                timeoutDuration: 4s
        instances:
            products:
                baseConfig: default
 
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9100
      client:
        registration:
          client-app:
            provider: spring
            client-id: gateway-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/authorized
            scope:
            - openid
            - profile
            client-name: client-app
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9100
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: msvc-oauth
            uri: lb://msvc-oauth
            predicates:
              - Path=/api/security/**
            filters:
              - StripPrefix=2
          - id: msvc-users
            uri: lb://msvc-users
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=2
          - id: msvc-products
            uri: lb://msvc-products
            predicates:
              - Path=/api/products/**
            # - Header=token, \d+
            # - Method=GET, POST
            # - Query=color
            # - Cookie=color, azul
            # - Header=Content-Type, application/json
            filters:
            #   - name: CircuitBreaker
            #     args: 
            #       name: products
            #       statusCodes: 500, 404
            #       fallbackUri: forward:/api/items/5
             - StripPrefix=2
              # - SampleCookie= "This is a sample cookie added in the gateway", user, dvalarez
          - id: msvc-items
            uri: lb://msvc-items
            predicates:
              - Path=/api/items/**
            filters:
              - StripPrefix=2
              - AddRequestHeader=token-request, aabbsjdfjsaj
              - AddResponseHeader=token-response, 234340823
              - AddRequestParameter=name, Andres
              - SetResponseHeader=Content-Type, text/plain